---
# tasks file for roles/docker

- name: "Install prerequisites for Docker"
  ansible.builtin.apt:
    name: "{{ docker.prerequisites }}"
    state: "present"
    update_cache: true

- name: "Add Docker's official GPG key"
  ansible.builtin.apt_key:
    url: "{{ docker.gpg_key }}"
    state: "present"

- name: "Add Docker repository"
  ansible.builtin.apt_repository:
    repo: "{{ docker.repo }}"
    state: "present"

- name: "Install Docker packages"
  ansible.builtin.apt:
    name: "{{ docker.packages }}"
    state: "present"
    update_cache: true

- name: "Ensure Docker service is running"
  ansible.builtin.service:
    name: "docker"
    state: "started"
    enabled: true
