---
# tasks file for roles/openscap-clean

- name: Find files that do not contain {{ ansible_facts.distribution | lower }}{{ ansible_facts.distribution_version | replace('.','') }} in the specified types
  find:
    paths: "{{ target_directory }}"
    patterns: "{{ file_types }}"
    recurse: yes
    excludes: "*{{ ansible_facts.distribution | lower }}{{ ansible_facts.distribution_version | replace('.','') }}*"
  register: files_to_delete

- name: Remove the files that do not match the pattern
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ files_to_delete.files }}"
