---
# defaults file for roles/openscap

scap_options_clean: false
scap_options_remediation: false

scap_packages:
  - "unzip"
  - "curl"
  - "libopenscap8"

openscap_download:
  openscap_github_release_api_url: "https://api.github.com/repos/ComplianceAsCode/content/releases/latest"
  dest: "/tmp/scap-security-guide"
  file_types_to_clean_up:
    - "*.sh"
    - "*.html"
    - "*.xml"
    - "*.txt"
    - "*.json"
    - "*.yml"
    - "*.cfg"

openscap_scan:
  ssg_file_name: "{{ openscap_download.dest }}/ssg-{{ ansible_facts.distribution | lower }}{{ ansible_facts.distribution_version | replace('.', '') }}-ds.xml"
  profile_search: "cis_level1_server"
  output_dir: "/tmp/"
  output_file_xml: "{{ inventory_hostname }}-result.xml"
  output_file_html: "{{ inventory_hostname }}-report.html"
  output_file_guide: "{{ inventory_hostname }}-guide.html"
  output_file_playbook: "{{ inventory_hostname }}-playbook.yml"
  output_file_bash: "{{ inventory_hostname }}-bash.sh"
  local_output_dir: "output/{{ the_date }}-openscap-results"
