---
# defaults file for roles/scap-install

scap_packages:
  - "unzip"
  - "curl"
  - "libopenscap8"

openscap_download:
  openscap_github_release_api_url: "https://api.github.com/repos/ComplianceAsCode/content/releases/latest"
  dest: "/tmp/scap-security-guide"
