---
# handlers file for roles/stack-config

- name: "Restart nginx"
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: "yes"

- name: "Restart php-fpm"
  ansible.builtin.service:
    name: "{{ php_service_name }}"
    state: restarted
    enabled: "yes"
