---
# defaults file for roles/php

php_packages:
  - php
  - php-cli
  - php-curl
  - php-gd
  - php-intl
  - php-mbstring
  - php-mysql
  - php-soap
  - php-xml
  - php-xmlrpc
  - php-zip
  - libapache2-mod-php

php_info: true

adminer:
  install: true
  path: /usr/share/adminer
  download: https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1-mysql.php
