---
# defaults file for roles/php

php_packages:
  - "php"
  - "libapache2-mod-php"
  - "php-mysql"
  - "php-cli"
  - "php-curl"
  - "php-gd"
  - "php-mbstring"
  - "php-xml"
  - "php-xmlrpc"
  - "php-soap"
  - "php-intl"
  - "php-zip"

php_info: true

adminer:
  install: true
  path: "/usr/share/adminer"
  download: "https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1-mysql.php"
