---

# Application and Resource Configuration
##################################################

debug_output: true

app:
  name: "learnansible" # don't get too creative
  region: "eu-west-1" # loction of where the resources are to be created
  env: "prod" # enviroment tag for the app
  public_dns_name: "learnansible" # the public dns name for the app

region: "{{ app.region }}"

# VPC and Subnets Configuration
##################################################

vpc:
  cidr_block: "10.0.0.0/23"
  dns_hostnames: true
  dns_support: true
  subnet_size: "27"
  subnets:
    - name: "ec2"
      role: "{{ subnet_role_compute }}"
    - name: "rds"
      role: "{{ subnet_role_database }}"
    - name: "efs"
      role: "{{ subnet_role_storage }}"    
    - name: "dmz"
      role: "{{ subnet_role_public }}"

subnet_role_compute: "compute"
subnet_role_database: "database"
subnet_role_storage: "storage"
subnet_role_public: "public"

# Resource Names
##################################################

vpc_name: "{{ app.name }}-{{ app.env }}-{{ playbook_dict.vpc }}"


# Dictionary
##################################################

playbook_dict:
  deployedBy: "Ansible"
  ansible_warning: "Resource managed by Ansible"
  vpc: "vpc"
  subnet: "subnet"
  