---
# tasks file for roles/azure

- name: "Create the resource group"
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ resource_group_name }}"
    location: "{{ location }}"
    tags: "{{ common_tags }}"
  register: "resource_group_output"

- name: "Debug - Resource Group result"
  ansible.builtin.debug:
    var: "resource_group_output"
  when: debug_output

- name: "Notify the team on Slack about the resource group status"
  include_tasks: slack_notify_generic.yml
  vars:
    resource_changed: "{{ resource_group_output.changed }}"
    resource_type: "Resource Group"
    resource_name: "{{ resource_group_output.state.name }}"
    resource_location: "{{ resource_group_output.state.location }}"
    azure_portal_link: "https://portal.azure.com/#resource{{ resource_group_output.state.id }}"
    resource_tags: >
      {% for key, value in resource_group_output.state.tags.items() %}
      *{{ key }}:* {{ value }}{% if not loop.last %}, {% endif %}
      {% endfor %}

- name: "Create the virtual network"
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ resource_group_output.state.name }}"
    name: "{{ virtual_network_name }}"
    address_prefixes: "{{ vnet_config.cidr_block }}"
    tags: "{{ common_tags }}"
  register: "virtual_network_output"

- name: "Debug - Virtual Network result"
  ansible.builtin.debug:
    var: "virtual_network_output"
  when: debug_output

- name: "Notify the team on Slack about the vnet status"
  include_tasks: slack_notify_generic.yml
  vars:
    resource_changed: "{{ virtual_network_output.changed }}"
    resource_type: "Virtual Network"
    resource_name: "{{ virtual_network_output.state.name }}"
    resource_location: "{{ virtual_network_output.state.location }}"
    azure_portal_link: "https://portal.azure.com/#resource{{ virtual_network_output.state.id }}"
    resource_tags: >
      {% for key, value in resource_group_output.state.tags.items() %}
      *{{ key }}:* {{ value }}{% if not loop.last %}, {% endif %}
      {% endfor %}

- name: "Add the subnets to the virtual network"
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ resource_group_output.state.name }}"
    name: "{{ item.name }}"
    address_prefix: "{{ item.subnet }}"
    virtual_network: "{{ virtual_network_output.state.name }}"
    service_endpoints:
      - service: "{{ item.service_endpoints }}"
  with_items: "{{ vnet_config.subnets }}"
  register: "subnet_output"

- name: "Debug - Subnets result"
  ansible.builtin.debug:
    var: "subnet_output"
  when: debug_output

- name: "Notify the team on Slack about each subnet status"
  include_tasks: slack_notify_generic.yml
  vars:
    resource_changed: "{{ item.changed }}"
    resource_type: "Subnet"
    resource_name: "{{ item.invocation.module_args.name }}"
    resource_location: "{{ virtual_network_output.state.location }}"
    azure_portal_link: "https://portal.azure.com/#resource{{ virtual_network_output.state.id }}"
    resource_tags: "N/A"
  loop: "{{ subnet_output.results }}"
