---
# tasks file for roles/zap

- name: "pull the image"
  community.docker.docker_image:
    name: "{{ image }}"
    source: pull

- name: create the folder which we will mount inside the container
  file:
    path: "{{ log.remote_folder }}"
    state: "directory"
    mode: "0777"

- name: "run the scan"
  community.docker.docker_container:
    detach: false
    auto_remove: false
    name: "wpscan"
    volumes: "{{ log.remote_folder }}:{{ log.remote_folder }}"
    image: "{{ image }}"
    command: "zap-baseline.py -t http://{{ ansible_host }} -g gen.conf -r {{ log.file }}"
  register: docker_scan

- name: "cop the report"
  ansible.builtin.fetch:
    src: "{{ log.remote_folder }}{{ log.file }}"
    dest: "{{ log.local_folder }}"
    flat: yes