---
# tasks file for roles/secrets

- name: "Check if the file secrets.yml exists"
  ansible.builtin.stat:
    path: "group_vars/secrets.yml"
  register: secrets_file
  delegate_to: "localhost"
  become: false

- name: "Generate the secrets.yml file using a template file if not exists"
  ansible.builtin.template:
    src: "secrets.yml.j2"
    dest: "group_vars/secrets.yml"
  when: secrets_file.stat.exists == false
  delegate_to: "localhost"
  become: false

- name: "Load the variables defined in the secrets.yml file"
  ansible.builtin.include_vars:
    file: "group_vars/secrets.yml"
  delegate_to: "localhost"
  become: false