---
- hosts: ansible_hosts
  gather_facts: true
  become: yes
  become_method: sudo

  vars_files:
    - "group_vars/common.yml"

  roles:
    - "roles/common"
    - "roles/apache"
    - "roles/mariadb"
    - "roles/php"