---

- name: "Destroy the AWS Environment created by the site.yml playbook"
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    state: "absent"
    your_public_ip: ""

  vars_files:
    - group_vars/common.yml

  tasks:

    - name: "Create a reversed list of the security group names"
      ansible.builtin.set_fact:
        security_groups_names_reversed: "{{ security_groups | map(attribute='name') | list | reverse }}"

    - name: "Delete the security groups"
      amazon.aws.ec2_security_group:
        name: "{{ item }}"
        region: "{{ region }}"
        state: "{{ state }}"
      with_items: "{{ security_groups_names_reversed }}"
      register: delete_security_groups
      until: "delete_security_groups is not failed"
      retries: 5
      delay: 2

    - name: "Get information about the VPC"
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: the_vpc

    - name: "Get information about the Route Table"
      amazon.aws.ec2_vpc_route_table_info:
        region: "{{ region }}"
        filters:
          "vpc-id": "{{ the_vpc.vpcs[0].id }}"
      register: the_route_tables
      when: the_vpc.vpcs | length > 0

    - name: "Delete the Route Table"
      amazon.aws.ec2_vpc_route_table:
        route_table_id: "{{ item.route_table_id }}"
        vpc_id: "{{ the_vpc.vpcs[0].id }}"
        region: "{{ region }}"
        lookup: "id"
        state: "{{ state }}"
      when: the_vpc.vpcs | length > 0 and not item.associations[0].main
      with_items: "{{ the_route_tables.route_tables }}"

    - name: "Delete the Internet Gateway"
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ the_vpc.vpcs[0].id }}"
        region: "{{ region }}"
        state: "{{ state }}"
      when: the_vpc.vpcs | length > 0

    - name: "Get information on the subnets"
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          "vpc-id": "{{ the_vpc.vpcs[0].id }}"
      register: the_subnets
      when: the_vpc.vpcs | length > 0

    - name: "Delete the subnets"
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ the_vpc.vpcs[0].id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        cidr: "{{ item.cidr_block }}"
      with_items: "{{ the_subnets.subnets }}"
      when: the_vpc.vpcs | length > 0

    - name: "Delete the VPC"
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ the_vpc.vpcs[0].id }}"
        region: "{{ region }}"
        state: "{{ state }}"
      when: the_vpc.vpcs | length > 0
