---
# defaults file for roles/docker

docker:
  prerequisites:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"
  gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
  repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  packages:
    - "docker-ce"
    - "docker-ce-cli"
