---

- hosts: ansible_hosts
  gather_facts: true
  become: yes
  become_method: sudo

  vars:
    ntp_servers:
      - "0.uk.pool.ntp.org"
      - "1.uk.pool.ntp.org"
      - "2.uk.pool.ntp.org"
      - "3.uk.pool.ntp.org"

  handlers:
    - name: "restart ntp"
      ansible.builtin.service:
        name: "ntp"
        state: "restarted"

  tasks:
    - ansible.builtin.debug:
        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
    - ansible.builtin.apt:
        name: "*"
        state: "latest"
        update_cache: "yes"
    - ansible.builtin.apt:
        state: "latest"
        pkg:
          - "ntp"
          - "sntp"
          - "ntp-doc"
    - ansible.builtin.template:
        src: "./ntp.conf.j2"
        dest: "/etc/ntp.conf"
      notify: "restart ntp"