---
# tasks file for roles/autoscaling

- name: search through all of our AMIs
  amazon.aws.ec2_ami_info:
    region: "{{ region }}"
    filters:
      name: "{{ ami_name }}-*"
  register: amiFind

- name: "find the last one we built"
  ansible.builtin.set_fact:
    amiSortFilter: "{{ amiFind.images | sort(attribute='creation_date') | last }}"

- name: "grab AMI ID and name of the most recent result"
  ansible.builtin.set_fact:
    our_ami_id: "{{ amiSortFilter.image_id }}"
    our_ami_name: "{{ amiSortFilter.name }}"

- name: "Debug: AMI ID"
  ansible.builtin.debug:
    msg: |
      "{{ our_ami_id }}
      "{{ our_ami_name }}" 
  when: debug_output

- name: "get information on the ec2 security group"
  amazon.aws.ec2_group_info:
    region: "{{ region }}"
    filters:
      group-name: "*{{ ec2_seach_string }}*"
  register: ec2_group_output

- name: "Debug: EC2 Security Group Info"
  ansible.builtin.debug:
    var: ec2_group_output
  when: debug_output

- name: "create the launch configuration"
  community.aws.autoscaling_launch_config:
    region: "{{ region }}"
    state: "{{ state }}"
    name: "{{ our_ami_name }}"
    image_id: "{{ our_ami_id }}"
    security_groups: [ "{{ ec2_group_output.security_groups[0].group_id }}" ]
    assign_public_ip: "{{ ec2.public_ip }}"
    instance_type: "{{ ec2.instance_type }}"
    volumes:
    - device_name: "/dev/xvda"
      volume_size: "10"
      volume_type: "gp2"
      delete_on_termination: true

- name: "find out the target group ARN"
  elb_target_group_info:
    region: "{{ region }}"
    names:
      - "{{ elb_target_group_name }}"
  register: elb_target_group_output

- name: "Debug: Target Group ARN"
  ansible.builtin.debug:
    var: elb_target_group_output
  when: debug_output

- name: "get information on the ec2 subnets"
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      tag:role: "*{{ subnet_role_compute }}*"
  register: ec2_subnet_output

- name: "Debug: EC2 Subnet Info"
  ansible.builtin.debug:
    var: ec2_subnet_output
  when: debug_output

- name: "create a list of subnet IDs"
  ansible.builtin.set_fact:
    subnet_ec2_ids: "{{ subnet_ec2_ids | default([]) + [ item.subnet_id ] }}"
  loop: "{{ ec2_subnet_output.subnets }}"

- name: "Debug: EC2 Subnet IDs"
  ansible.builtin.debug:
    var: subnet_ec2_ids
  when: debug_output

- name: create / update the auto-scaling group using the launch configuration we just created
  community.aws.ec2_asg:
    region: "{{ region }}"
    state: "{{ state }}"
    name: "{{ asg_name }}"
    target_group_arns: [ "{{ elb_target_group_output.target_groups[0].target_group_arn }}" ]
    launch_config_name: "{{ our_ami_name }}"
    min_size: "{{ ec2.asg.min_size }}"
    max_size: "{{ ec2.asg.max_size }}"
    desired_capacity: "{{ ec2.asg.desired_capacity }}"
    health_check_period: "{{ ec2.asg.health_check_period }}"
    health_check_type: "{{ ec2.asg.health_check_type }}"
    replace_all_instances: "{{ ec2.asg.replace_all_instances }}"
    replace_batch_size: "{{ ec2.asg.replace_batch_size }}"
    vpc_zone_identifier: "{{ subnet_ec2_ids }}"
    wait_for_instances: "{{ ec2.asg.wait_for_instances }}"
    wait_timeout: "{{ ec2.asg.wait_timeout }}"
    tags:
      - key: "Name"
        value: "{{ asg_name }}"
        propagate_at_launch: true
      - key: "Project"
        value: "{{ app.name }}"
        propagate_at_launch: true
      - key: "Environment"
        value: "{{ app.env }}"
        propagate_at_launch: true
      - key: "Deployed_by"
        value: "Ansible"
        propagate_at_launch: true
  register: ec2_asg_output

- name: "Debug: Auto Scaling Group Output"
  ansible.builtin.debug:
    var: ec2_asg_output
  when: debug_output