---

- name: Bootstrap the Windows instance
  hosts: ansible_hosts
  gather_facts: true

  vars_files:
    - group_vars/common.yml

  roles:
    - roles/iis
    - roles/dotnet
    - roles/user
    - roles/choc
    - roles/info