---
# tasks file for roles/subnets

- name: "Get some information on the available zones"
  amazon.aws.aws_az_info:
    region: "{{ region }}"
  register: zones_output

- name: "Debug - Zones result"
  ansible.builtin.debug:
    var: "zones_output"
  when: debug_output

- name: "Create all subnets"
  include_tasks: create_subnet.yml
  loop: "{{ vpc.subnets }}"
  loop_control:
    loop_var: subnet_item
    index_var: subnet_index
  vars:
    subnet_name: "{{ subnet_item.name }}"
    az_zones_from_main: "{{ zones_output }}"
  register: subnet_output  

- name: "Debug - All Subnets"
  ansible.builtin.debug:
    var: "subnet_output"
  when: debug_output