---

- name: "Install and confugure WordPress and supporting software"
  hosts: "ansible_hosts"
  gather_facts: true
  become: true
  become_method: "ansible.builtin.sudo"

  vars_files:
    - "group_vars/common.yml"

  roles:
    - "stack_install"
    - "stack_config"
    - "wordpress"
