---
- hosts: ansible_hosts
  gather_facts: true
  become: true
  become_method: sudo

  vars_files:
    - "group_vars/common.yml"

  roles:
    - "roles/stack-install"
    - "roles/stack-config"
    - "roles/wordpress"