---
# tasks file for roles/stack-install

# Run apt-get update and upgrade
- name: "update apt-cache and upgrade packages"
  ansible.builtin.apt:
    name: "*"
    state: "latest"
    update_cache: "yes"

# Add repository keys
- name: "add the apt keys from a URL"
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: "present"
  with_items: "{{ repo_keys_url }}"

# Add repository packages
- name: "install the repo packages"
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: "present"
    update_cache: "yes"
  with_items: "{{ repo_packages }}"

# Install system, extra and stack packages
- name: "update cache and install the stack packages"
  ansible.builtin.apt:
    state: "latest"
    update_cache: "yes"
    pkg: "{{ system_packages + extra_packages + stack_packages  }}"
